In [1]:
from pyad.autodiff import newAutoDiff, newAutoDiffLike, squareVector
import numpy as np

In [2]:
x = newAutoDiff(np.array([1.0, 3.0]), np.array([[2.0, 2.0]]).T)

In [3]:
x

<pyad.autodiff.AutoDiffVectorMax73; proxy of <Swig Object of type 'AutoDiffWrapper< Eigen::Matrix< double,Eigen::Dynamic,1,0,73 >,Eigen::Dynamic,1 > *' at 0x110469600> >

In [4]:
x.value()

array([[ 1.],
       [ 3.]])

In [5]:
x.derivatives()

array([[ 2.],
       [ 2.]])

In [6]:
y = newAutoDiffLike(x, [5., 6.])

In [7]:
y

<pyad.autodiff.AutoDiffVectorMax73; proxy of <Swig Object of type 'AutoDiffWrapper< Eigen::Matrix< double,Eigen::Dynamic,1,0,73 >,Eigen::Dynamic,1 > *' at 0x110469810> >

In [8]:
z = x + y

In [9]:
print z.value()

[[ 6.]
 [ 9.]]


In [11]:
print z.derivatives()

[[ 2.]
 [ 2.]]


In [12]:
w = squareVector(x)

In [13]:
print w.value()

[[ 1.]
 [ 9.]]


In [14]:
print w.derivatives()

[[  4.]
 [ 12.]]


In [15]:
big = newAutoDiff(np.random.rand(75,1))

In [16]:
big

<pyad.autodiff.AutoDiffVectorDynamic; proxy of <Swig Object of type 'AutoDiffWrapper< Eigen::VectorXd,Eigen::Dynamic,1 > *' at 0x110497150> >

In [17]:
big.derivatives()

array([[ 1.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  1.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  1., ...,  0.,  0.,  0.],
       ..., 
       [ 0.,  0.,  0., ...,  1.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  1.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  1.]])

In [18]:
np.allclose((big + 2.0).value(), big.value() + 2.0)

True

In [19]:
np.allclose((big + 2.0).derivatives(), big.derivatives())

True

In [20]:
np.allclose((big * 2.0).derivatives(), 2.0 * big.derivatives())

True

In [ ]:
x.value()

In [ ]:
x.derivatives()

In [ ]:
y = pyad.autodiff.squareVector(x)

In [ ]:
y.value()

In [ ]:
y.derivatives()

In [ ]:
z = x + y

In [ ]:
z.value()

In [ ]:
z.derivatives()

In [ ]:
w = x + 1

In [ ]:
w.value()

In [ ]:
w.derivatives()

In [ ]:
x = ad.adnumber(3.0)

In [ ]:
x2 = pyad.autodiff.square(x)

In [ ]:
x2, x2.d(x)

In [ ]:
z = ad.adnumber(np.array([1,2,3,4]))

In [ ]:
z.dtype

In [ ]:
a = np.array([1,2,3])

In [ ]:
a[0]

In [ ]:
a.ndim

In [ ]:
np.prod([1,2,3])

In [ ]:
np.zeros((3,3,3)).size

In [ ]:
import taylor; reload(taylor)

In [ ]:
t = taylor.TaylorVar(np.array([1,2,3]))

In [ ]:
t.derivatives[0][1]

In [ ]:
v = ad.adnumber(t.value)
a = t.to_adnumber(v)

In [ ]:
t2 = taylor.TaylorVar.from_adnumber(a, v)

In [ ]:
t2.derivatives[0], t2.value

In [ ]:
t.derivatives[0]

In [ ]:
np.asarray(a, dtype=np.object)

In [ ]:
np.sum(a).d(v[0])

In [ ]:
(a **2)[1].d(v[1])