In [4]:
import pyad.autodiff

In [14]:
import numpy as np

In [15]:
import ad

In [16]:
x = ad.adnumber(3.0)

In [17]:
x2 = pyad.autodiff.square(x)

in python, after square
looking up autodiff keys: [ad(3.0)]


In [18]:
x2, x2.d(x)

(ad(9.0), 6.0)

In [19]:
z = ad.adnumber(np.array([1,2,3,4]))

In [23]:
z.dtype

dtype('O')

In [24]:
a = np.array([1,2,3])

In [26]:
a[0]

1

In [27]:
a.ndim

1

In [30]:
np.prod([1,2,3])

6

In [32]:
np.zeros((3,3,3)).size

27

In [143]:
import taylor; reload(taylor)

<module 'taylor' from 'taylor.py'>

In [144]:
t = taylor.TaylorVar(np.array([1,2,3]))

In [145]:
t.derivatives[0][1]

array([ 0.,  1.,  0.])

In [146]:
v = ad.adnumber(t.value)
a = t.to_adnumber(v)

In [147]:
t2 = taylor.TaylorVar.from_adnumber(a, v)

In [150]:
t2.derivatives[0], t2.value

(array([array([ 1.,  0.,  0.]), array([ 0.,  1.,  0.]),
        array([ 0.,  0.,  1.])], dtype=object), array([ 1.,  2.,  3.]))

In [149]:
t.derivatives[0]

array([array([ 1.,  0.,  0.]), array([ 0.,  1.,  0.]),
       array([ 0.,  0.,  1.])], dtype=object)

In [136]:
np.asarray(a, dtype=np.object)

array([ad(1), ad(2), ad(3)], dtype=object)

In [122]:
np.sum(a).d(v[0])

1.0

In [156]:
(a **2)[1].d(v[1])

4.0