In [1]:
import pyad.autodiff
import numpy as np

In [2]:
x = pyad.autodiff.AutoDiffVectorDynamic(np.array([1.0, 3.0]), np.array([[2.0], [5.0]]))

In [3]:
x.value()

array([[ 1.],
       [ 3.]])

In [4]:
x.derivatives()

array([[ 2.],
       [ 5.]])

In [5]:
y = pyad.autodiff.squareVector(x)

In [6]:
y.value()

array([[ 1.],
       [ 9.]])

In [7]:
y.derivatives()

array([[  4.],
       [ 30.]])

In [8]:
z = x + y

In [9]:
z.value()

array([[  2.],
       [ 12.]])

In [10]:
z.derivatives()

array([[  6.],
       [ 35.]])

In [11]:
w = x + 1

In [12]:
w.value()

array([[ 2.],
       [ 4.]])

In [13]:
w.derivatives()

array([[ 2.],
       [ 5.]])

In [ ]:
x = ad.adnumber(3.0)

In [ ]:
x2 = pyad.autodiff.square(x)

In [ ]:
x2, x2.d(x)

In [ ]:
z = ad.adnumber(np.array([1,2,3,4]))

In [ ]:
z.dtype

In [ ]:
a = np.array([1,2,3])

In [ ]:
a[0]

In [ ]:
a.ndim

In [ ]:
np.prod([1,2,3])

In [ ]:
np.zeros((3,3,3)).size

In [ ]:
import taylor; reload(taylor)

In [ ]:
t = taylor.TaylorVar(np.array([1,2,3]))

In [ ]:
t.derivatives[0][1]

In [ ]:
v = ad.adnumber(t.value)
a = t.to_adnumber(v)

In [ ]:
t2 = taylor.TaylorVar.from_adnumber(a, v)

In [ ]:
t2.derivatives[0], t2.value

In [ ]:
t.derivatives[0]

In [ ]:
np.asarray(a, dtype=np.object)

In [ ]:
np.sum(a).d(v[0])

In [ ]:
(a **2)[1].d(v[1])